ValueError: All arguments should have the same length. The length of argument `y` is 2, whereas the length of previously-processed arguments ['Date'] is 2515
Traceback:
File "C:\Users\ASUS\Desktop\dsfm_GEM\ok.py", line 117, in <module>
    st.plotly_chart(plot_regime_chart(regime_data), use_container_width=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\ASUS\Desktop\dsfm_GEM\ok.py", line 50, in plot_regime_chart
    fig = px.line(df, x=df.index, y=close_column, color='Regime', title='Portfolio Performance with Market Regimes')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\ASUS\AppData\Roaming\Python\Python312\site-packages\plotly\express\_chart_types.py", line 270, in line
    return make_figure(args=locals(), constructor=go.Scatter)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\ASUS\AppData\Roaming\Python\Python312\site-packages\plotly\express\_core.py", line 2479, in make_figure
    args = build_dataframe(args, constructor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\ASUS\AppData\Roaming\Python\Python312\site-packages\plotly\express\_core.py", line 1727, in build_dataframe
    df_output, wide_id_vars = process_args_into_dataframe(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\ASUS\AppData\Roaming\Python\Python312\site-packages\plotly\express\_core.py", line 1373, in process_args_into_dataframe
    raise ValueError(